/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    copy: typeof import('./components/MovieListItem copy.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MovieCardDetail: typeof import('./components/MovieCardDetail.vue')['default']
    MovieCartDetail: typeof import('./components/MovieCartDetail.vue')['default']
    MovieListItem: typeof import('./components/MovieListItem.vue')['default']
    MoviePlaces: typeof import('./components/MoviePlaces.vue')['default']
    MovieShows: typeof import('./components/MovieShows.vue')['default']
    MovieShowsList: typeof import('./components/MovieShowsList.vue')['default']
    MoviesSearch: typeof import('./components/MoviesSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
